"""added created_at & updated_at fields in Todo

Revision ID: f56ed6acd67a
Revises: 3c0055afcd58
Create Date: 2024-07-24 08:55:41.415012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56ed6acd67a'
down_revision: Union[str, None] = '3c0055afcd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TABLE IF NOT EXISTS todos_new (id INTEGER PRIMARY KEY, title TEXT NOT NULL, description TEXT, state TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL);")
    op.execute("INSERT INTO todos_new (id, title, description, state) SELECT id, title, description, state FROM todos;")
    op.drop_table("todos")
    op.rename_table("todos_new", "todos")
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    # ### end Alembic commands ###
